# Generated by Django 5.1.7 on 2025-03-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_stream_movie_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stream',
        ),
    ]
