# Generated by Django 5.1.7 on 2025-03-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_remove_movie_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
