# Generated by Django 5.1.7 on 2025-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0010_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='num_rating',
            field=models.IntegerField(default=0),
        ),
    ]
