# Generated by Django 5.1.7 on 2025-03-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0012_streamplatform_remove_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='number_rating',
        ),
    ]
