# Generated by Django 5.1.7 on 2025-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0013_remove_movie_avg_rating_remove_movie_number_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
